server:
  port: 8081


spring:
 thymeleaf:
   cache: false
   prefix: classpath:/templates/
   suffix: .html
   encoding: UTF-8
   content-type: text/html
   mode: HTML5
 datasource:
   name: test
   url: jdbc:mysql://127.0.0.1:3306/utcdemo?useSSL=false
   username: root
   password: password
   # 使用druid数据源
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver

#   filters: stat
#   maxActive: 20
#   initialSize: 1
#   maxWait: 60000
#   minIdle: 1
#   timeBetweenEvictionRunsMillis: 60000
#   minEvictableIdleTimeMillis: 300000
#   validationQuery: select 'x'
#   testWhileIdle: true
#   testOnBorrow: false
#   testOnReturn: false
#   poolPreparedStatements: true
#   maxOpenPreparedStatements: 20



mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.ntt.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql